"""model_response_cache: spec §6.5's response cache.

A separate table from `verification_cache` rather than a widening of it. That one is Lean-specific
-- keyed on a base env and a declaration source, storing a `verdict_kind` -- and none of those mean
anything about a model completion. Sharing a table would give a key space where a Lean check and a
sampled completion could collide, and a row where half the columns are always NULL.

No enum columns, so this one does not need the explicit `DROP TYPE` the initial migration's
`downgrade()` carries (see CLAUDE.md's database notes). Verified rather than assumed: applied,
`alembic check`ed for drift, downgraded and re-upgraded against a real PostgreSQL 16.

Revision ID: 3bd1fe9a53fb
Revises: ddd0ce64c4a4
Create Date: 2026-09-10 21:06:56.876565

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bd1fe9a53fb"
down_revision: str | Sequence[str] | None = "ddd0ce64c4a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_response_cache",
        sa.Column("cache_key", sa.LargeBinary(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("weights_revision", sa.Text(), nullable=True),
        sa.Column("tokenizer_revision", sa.Text(), nullable=True),
        sa.Column("prompt_token_ids_blob", sa.LargeBinary(), nullable=True),
        sa.Column("completions_blob", sa.LargeBinary(), nullable=False),
        sa.Column("n_completions", sa.Integer(), nullable=False),
        sa.Column("elapsed_ms", sa.BigInteger(), nullable=False),
        sa.Column("hits", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    op.create_index(
        op.f("ix_model_response_cache_model_id"), "model_response_cache", ["model_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_response_cache_model_id"), table_name="model_response_cache")
    op.drop_table("model_response_cache")
    # ### end Alembic commands ###
