"""obligation.bundle_sha; sealed_olean_sha nullable

Two deviations from spec's own §5.2 DDL, both because the DDL and §4.1 cannot both hold.

`bundle_sha` is new. Spec §4.1 names the generated bundle `LeanAgent/Goals/Bundle_<digest>.lean`,
where the digest is of the bundle *source* -- that is what tells a worker which module to import
in order to link. `sealed_olean_sha` is the *compiled* artifact's digest and cannot serve: you
would have to build the file to learn its name.

`sealed_olean_sha` becomes nullable. Spec declares it `bytea NOT NULL`, but §4.1 also says "the
`.olean` artifact is produced lazily out of band ... the hot path never waits on the build
system" -- so at obligation-creation time there is nothing to put there. NULL means "not yet
materialized", and it is self-enforcing rather than merely documented: `mark_proved` compares
`v.sealed_olean_sha_observed = o.sealed_olean_sha`, which is NULL (never true) while this is NULL,
so an obligation whose bundle was never built cannot reach `proved`.

`downgrade()` restores NOT NULL and will fail if any unmaterialized obligation exists. That is
correct rather than a defect -- there is no honest value to backfill.

Revision ID: c7576a782854
Revises: f5abd93c3975
Create Date: 2026-09-10 08:29:50.999289

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c7576a782854"
down_revision: str | Sequence[str] | None = "f5abd93c3975"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("obligation", sa.Column("bundle_sha", sa.LargeBinary(), nullable=True))
    op.alter_column(
        "obligation", "sealed_olean_sha", existing_type=postgresql.BYTEA(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "obligation", "sealed_olean_sha", existing_type=postgresql.BYTEA(), nullable=False
    )
    op.drop_column("obligation", "bundle_sha")
    # ### end Alembic commands ###
