"""run.reassembly_blob

Spec §6.3 step 6 materializes "the file with each `sorry` replaced", which needs the reassembly
text `/v1/decompose` produced. Spec has a `reassembly_blob` already -- on `obligation_edge`, "on
the group, not the child" -- but that is a *decomposition group*'s reassembly, produced when a
policy decomposes an obligation. A submitted file's reassembly is a different artifact: it exists
before any policy runs, has no parent obligation to hang off, and covers every root at once. It
belongs to the run.

NULL for a bare-statement submission, which has no file to reassemble.

Revision ID: ddd0ce64c4a4
Revises: c7576a782854
Create Date: 2026-09-10 11:52:07.412851

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddd0ce64c4a4"
down_revision: str | Sequence[str] | None = "c7576a782854"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run", sa.Column("reassembly_blob", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("run", "reassembly_blob")
    # ### end Alembic commands ###
