"""initial schema

Revision ID: f5abd93c3975
Revises:
Create Date: 2026-09-09 12:17:37.800186

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5abd93c3975"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_env",
        sa.Column("digest", sa.LargeBinary(), nullable=False),
        sa.Column("recipe", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("toolchain_rev", sa.Text(), nullable=False),
        sa.Column("mathlib_rev", sa.Text(), nullable=False),
        sa.Column("snapshot_path", sa.Text(), nullable=True),
        sa.Column("snapshot_bytes", sa.BigInteger(), nullable=True),
        sa.Column("curated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_table(
        "blob",
        sa.Column("sha256", sa.LargeBinary(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("sha256"),
    )
    op.create_table(
        "verification_cache",
        sa.Column("cache_key", sa.LargeBinary(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "proved", "refuted", "errors", "timeout", "oom", "infra_error", name="verdict_kind"
            ),
            nullable=False,
        ),
        sa.Column("axioms", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("messages_blob", sa.LargeBinary(), nullable=True),
        sa.Column("infotree_blob", sa.LargeBinary(), nullable=True),
        sa.Column("elapsed_ms", sa.BigInteger(), nullable=False),
        sa.Column("toolchain_rev", sa.Text(), nullable=False),
        sa.Column("mathlib_rev", sa.Text(), nullable=False),
        sa.Column("hits", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("base_env_digest", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("manifest_hash", sa.LargeBinary(), nullable=False),
        sa.Column("allow_sorry", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "axiom_allowlist",
            postgresql.ARRAY(sa.Text()),
            server_default="{propext,Classical.choice,Quot.sound}",
            nullable=False,
        ),
        sa.Column("max_depth", sa.Integer(), server_default="6", nullable=False),
        sa.Column("budget_tokens", sa.BigInteger(), nullable=True),
        sa.Column("budget_wallclock_ms", sa.BigInteger(), nullable=True),
        sa.Column("budget_kernel_ms", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_env_digest"],
            ["base_env.digest"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_tenant_id"),
        "run",
        ["tenant_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "obligation",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_progress",
                "decomposed",
                "proved",
                "failed",
                "blocked",
                "abandoned",
                name="obligation_status",
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column("priority", sa.Double(), server_default="0", nullable=False),
        sa.Column("is_root", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("base_env_digest", sa.LargeBinary(), nullable=False),
        sa.Column("goal_digest", sa.LargeBinary(), nullable=False),
        sa.Column("sealed_olean_sha", sa.LargeBinary(), nullable=False),
        sa.Column("goal_src", sa.Text(), nullable=False),
        sa.Column("decl_name", sa.Text(), nullable=False),
        sa.Column(
            "admission",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("budget_attempts", sa.Integer(), server_default="8", nullable=False),
        sa.Column("budget_tokens", sa.BigInteger(), server_default="1000000", nullable=False),
        sa.Column("budget_kernel_ms", sa.BigInteger(), server_default="600000", nullable=False),
        sa.Column("spent_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("spent_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("spent_kernel_ms", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("proof_blob", sa.LargeBinary(), nullable=True),
        sa.Column("created_by_policy", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_env_digest"],
            ["base_env.digest"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_obligation_goal_digest"), "obligation", ["goal_digest"], unique=False)
    op.create_index(
        "obligation_schedulable",
        "obligation",
        ["run_id", "status", sa.literal_column("priority DESC"), "depth"],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "attempt",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("obligation_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "claimed",
                "running",
                "succeeded",
                "failed",
                "expired",
                "infra_error",
                name="attempt_status",
            ),
            server_default="claimed",
            nullable=False,
        ),
        sa.Column("policy_id", sa.Text(), nullable=False),
        sa.Column("policy_config_hash", sa.LargeBinary(), nullable=False),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tokens_in", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("tokens_out", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("kernel_ms", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("wallclock_ms", sa.BigInteger(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["obligation_id"], ["obligation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "attempt_expired",
        "attempt",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('claimed', 'running')"),
    )
    op.create_index(
        op.f("ix_attempt_obligation_id"),
        "attempt",
        ["obligation_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "obligation_edge",
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("reassembly_blob", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(["child_id"], ["obligation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["obligation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parent_id", "child_id", "group_id"),
    )
    op.create_index(
        op.f("ix_obligation_edge_child_id"), "obligation_edge", ["child_id"], unique=False
    )
    op.create_index(
        op.f("ix_obligation_edge_group_id"), "obligation_edge", ["group_id"], unique=False
    )
    op.create_table(
        "tool_call",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("server", sa.Text(), nullable=False),
        sa.Column("tool", sa.Text(), nullable=False),
        sa.Column(
            "trust",
            sa.Enum("kernel_checked", "advisory", "retrieval", name="trust_class"),
            nullable=False,
        ),
        sa.Column("args_blob", sa.LargeBinary(), nullable=False),
        sa.Column("result_blob", sa.LargeBinary(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=12, scale=6), server_default="0", nullable=False
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempt.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tool_call_attempt_id"), "tool_call", ["attempt_id", "step_index"], unique=False
    )
    op.create_table(
        "trajectory",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provenance",
            sa.Enum(
                "open_weights", "symbolic", "human", "closed_api_eval_only", name="provenance_class"
            ),
            nullable=False,
        ),
        sa.Column("model_id", sa.Text(), nullable=True),
        sa.Column("model_weights_hash", sa.Text(), nullable=True),
        sa.Column("tokenizer_revision", sa.Text(), nullable=True),
        sa.Column("sampling", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.Column("steps_blob", sa.LargeBinary(), nullable=False),
        sa.Column("token_ids_blob", sa.LargeBinary(), nullable=True),
        sa.Column("logprobs_blob", sa.LargeBinary(), nullable=True),
        sa.Column("n_steps", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempt.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("attempt_id"),
    )
    op.create_index(
        op.f("ix_trajectory_provenance"), "trajectory", ["provenance", "model_id"], unique=False
    )
    op.create_table(
        "verdict",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("obligation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "proved", "refuted", "errors", "timeout", "oom", "infra_error", name="verdict_kind"
            ),
            nullable=False,
        ),
        sa.Column("link_ok", sa.Boolean(), nullable=False),
        sa.Column("replay_ok", sa.Boolean(), nullable=False),
        sa.Column("axiom_audit_ok", sa.Boolean(), nullable=False),
        sa.Column("sealed_olean_sha_observed", sa.LargeBinary(), nullable=True),
        sa.Column("axioms", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("kernels_agreeing", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("messages_blob", sa.LargeBinary(), nullable=True),
        sa.Column("infotree_blob", sa.LargeBinary(), nullable=True),
        sa.Column("proof_blob", sa.LargeBinary(), nullable=True),
        sa.Column("elapsed_ms", sa.BigInteger(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("toolchain_rev", sa.Text(), nullable=False),
        sa.Column("mathlib_rev", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempt.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["obligation_id"], ["obligation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("attempt_id"),
    )
    op.create_index(
        op.f("ix_verdict_obligation_id"), "verdict", ["obligation_id", "kind"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verdict_obligation_id"), table_name="verdict")
    op.drop_table("verdict")
    op.drop_index(op.f("ix_trajectory_provenance"), table_name="trajectory")
    op.drop_table("trajectory")
    op.drop_index(op.f("ix_tool_call_attempt_id"), table_name="tool_call")
    op.drop_table("tool_call")
    op.drop_index(op.f("ix_obligation_edge_group_id"), table_name="obligation_edge")
    op.drop_index(op.f("ix_obligation_edge_child_id"), table_name="obligation_edge")
    op.drop_table("obligation_edge")
    op.drop_index(op.f("ix_attempt_obligation_id"), table_name="attempt")
    op.drop_index(
        "attempt_expired",
        table_name="attempt",
        postgresql_where=sa.text("status IN ('claimed', 'running')"),
    )
    op.drop_table("attempt")
    op.drop_index(
        "obligation_schedulable",
        table_name="obligation",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(op.f("ix_obligation_goal_digest"), table_name="obligation")
    op.drop_table("obligation")
    op.drop_index(op.f("ix_run_tenant_id"), table_name="run")
    op.drop_table("run")
    op.drop_table("verification_cache")
    op.drop_table("blob")
    op.drop_table("base_env")
    # ### end Alembic commands ###

    # Alembic's autogenerate does not emit `DROP TYPE` for Postgres native enums on downgrade --
    # confirmed empirically: downgrading then re-upgrading failed with "type already exists",
    # since dropping the tables that used them leaves the enum types themselves orphaned in the
    # database. Each one must be dropped explicitly, after every table referencing it is gone.
    for enum_name in (
        "obligation_status",
        "attempt_status",
        "verdict_kind",
        "trust_class",
        "provenance_class",
    ):
        op.execute(f"DROP TYPE {enum_name}")
